version: '3.4'

services:
  netcore-skeleton-api:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    environment:
      - 'ASPNETCORE_ENVIRONMENT=Development'
    ports:
      - '8080:5000'
    depends_on:
      - postgres-skeleton-db
    restart: on-failure
      
  postgres-skeleton-db:
    image: postgres
    env_file:
      - postgres.dev.env

  dotnet-skeleton-tests:
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    volumes:
      - ./CoverageReport:/CoverageReport
    depends_on:
      - postgres-skeleton-db
